### ISSUE TITLE
Feature: Customize colors for types

### ISSUE THREAD

**Issue by MichaelYuhe** [MichaelYuhe/ai-group-tabs#47]
Now we use default colors with Chrome API, it might be better to let user decide which color to use for a specified type.

Maybe we can add a color picker between the "type inputbar" and the "delete button"
<img width="359" alt="image" src="https://github.com/MichaelYuhe/ai-group-tabs/assets/63531512/2d51e0d9-8932-4a10-9932-35a74ba05e7a">

**Comment by flamintune** [comment]
Hi @MichaelYuhe,

I came across the feature request for customizing colors for types (#47) and found it very interesting. I noticed that the issue was opened 6 hours ago and there haven't been any comments indicating that someone is already working on it.

If nobody has taken this up yet, I would be delighted to contribute to this feature. I have some ideas on how to implement a color picker to let users choose their preferred colors for specified types, and I'd be eager to discuss this further and start working on it.

Additionally, I've been giving some thought to the feature implementation. I suggest providing a dropdown menu with a predefined set of colors instead of a full color picker. A color picker might seem a bit cumbersome for users who prefer a quicker selection process, and a dropdown could streamline the user experience by offering a curated choice of colors that fit well with the application's design, while still providing an option for customization when needed.
![image](https://github.com/MichaelYuhe/ai-group-tabs/assets/79519446/7c393fc7-44e6-429b-ac2a-2aa4aef391dc)


Please let me know if this feature is still unassigned, and if there are any specific guidelines or contribution standards you'd like me to follow.

Looking forward to your response and the opportunity to contribute to the project.

**Comment by MichaelYuhe** [comment]
Hey @flamintune , excited to see someone else is interested in this feature too! And your implementation is also what it should be look like in my mind.
I've investigated this issue earlier today, I found that it seems we are only allowed to use the 8 colors that chrome provided?
Have you tried to the color picker yet? Can the color besides the default colors work?

**Comment by lawvs** [comment]
In fact, the TabGroup API only has a few colors to choose from. I believe that using a design similar to Chrome's is sufficient.

![Screenshot 2023-12-11 at 21 44 48](https://github.com/MichaelYuhe/ai-group-tabs/assets/18554747/4b174818-d0d9-46a4-ba41-322861669fec)

```ts
    export type ColorEnum = 'grey' | 'blue' | 'red' | 'yellow' | 'green' | 'pink' | 'purple' | 'cyan';

    export interface TabGroup {
        /** Whether the group is collapsed. A collapsed group is one whose tabs are hidden. */
        collapsed: boolean;
        /** The group's color. */
        color: ColorEnum;
        /** The ID of the group. Group IDs are unique within a browser session. */
        id: number;
        /** Optional. The title of the group. */
        title?: string | undefined;
        /** The ID of the window that contains the group. */
        windowId: number;
    }
```

**Comment by MichaelYuhe** [comment]
This would be great!

**Comment by flamintune** [comment]
Indeed, the TabGroup API currently limits us to using only the colors provided by Chrome.

I have tried using RGB and HSL values to set colors, but these values do not take effect—only the preset color options can be used.

As a next step, I plan to develop a dropdown color selector based on Chrome's preset colors. This way, users will be able to quickly choose from the available options without having to remember specific color names. I'll share my progress in upcoming updates.

**Comment by MichaelYuhe** [comment]
Maybe you two can discuss about how to design this dropdown's ui/ux 😄 
If there is anything that needs my help just mention me!

**Comment by flamintune** [comment]
![image](https://github.com/MichaelYuhe/ai-group-tabs/assets/79519446/a13fc90e-613b-4d53-96b8-8375f286bbf7)

Firstly, I would like to extend my sincerest apologies for the delay in implementing this feature. Your patience and understanding are greatly appreciated. I am pleased to announce that the development of the custom color feature has been successfully completed. However, I would like to bring your attention to a couple of points for further consideration:

In terms of the color editing interface, I have implemented a "click to the next" mechanism as opposed to using a dropdown menu. My rationale is based on the assumption that users are generally more concerned with the ability to differentiate between colors rather than the method of selection. I initially tried a dropdown approach, but it didn't meet our aesthetic standards. Consequently, I opted for a more streamlined solution that allows users to navigate to the next color option.

With regards to the storage of color values, my original intention was to integrate these values within the types data structure. However, due to my current level of familiarity with the codebase, I encountered some challenges. To ensure progress, I have provisionally created a separate colors field dedicated to storing the color associated with each type.

Additionally, I have encountered an unexpected issue with Tailwind CSS where the bg-color-500 class does not appear to be functioning as anticipated. As a temporary workaround, I have applied inline styles directly within the code to achieve the desired styling effect.

I hope these choices align well with our project goals and I am open to any feedback or suggestions you may have. Thank you for your understanding and support.

**Comment by MichaelYuhe** [comment]
Hey @flamintune don't be sorry for this, I really appreciate your enthusiasm and contribution.
Can your draft a pull request so that I can see your code and test it myself?
